### ISSUE TITLE
Test loading csv without header

### ISSUE THREAD

**Issue by skatedplrn** [deeplearninc/auger-ml#100]

**Comment by StanislavVolodarskiy** [comment]
pandas.read_csv has header parameter: """
@>>> df = pd.read_csv('tests/fixtures/nba_player_games_small.csv', header=None)
@>>> df.columns
Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            109, 110, 111, 112, 113, 114, 115, 116, 117, 118],
           dtype='int64', length=119)
""".

**Comment by StanislavVolodarskiy** [comment]
Before using header=None we have to be sure that CSV file actually does not have header. Otherwise we will get header line as garbage in data frame.
