### ISSUE TITLE
fold files are too big

### ISSUE THREAD

**Issue by skatedplrn** [deeplearninc/auger-ml#103]
We use np.savez and looks like it save doubles as 64 bit, so fold file is 3-4 time bigger then csv:
covtype.data.csv - 75 MB
fold0.npz - 225 MB

**Comment by StanislavVolodarskiy** [comment]
numpy.savez_compressed ?
https://docs.scipy.org/doc/numpy/reference/generated/numpy.savez_compressed.html#numpy.savez_compressed

**Comment by StanislavVolodarskiy** [comment]
np.savez tested on covtype.data.csv:
average save time 13.55 s
fold files size 771587386
load time: 0.23 s

np.savez_compressed tested on covtype.data.csv:
average save time 15.29 s
fold files size 45228334
load time: 0.42 s

**Comment by StanislavVolodarskiy** [comment]
The next experiment is to cast numpy arrays to float32:
np.savez_compressed tested on covtype.data.csv:
average save time 9.30 s
fold files size 39523726
load time: 0.26 s

**Comment by StanislavVolodarskiy** [comment]
Please check https://github.com/deeplearninc/auger-ml/pull/104
