### ISSUE TITLE
Export model to notebook

### ISSUE THREAD

**Issue by skatedplrn** [deeplearninc/auger-ml#107]
Use AugerML.predict_by_model method
and path to predict data in files folder

**Comment by derekflint** [comment]
@skatedplrn I'm trying to create notebook script to do predictions. this returns empty string. Can you let me know if I'm missing something. uid is from promoted pipeline i did manually.


from auger_ml.AugerML import AugerML
from auger_notebook.models.regression.file_utils import create_file_utils
import os
import json
from auger_ml.Config import *

config = Config(None, None)
config.loadEnvs()
initConfig(config)

file_utils = create_file_utils(config)

uid = '3FC776483EE545B'
model_path = file_utils.project_models_abs_path

test_path = os.path.join(file_utils.project_files_abs_path,'iris_data.csv')

options_path = os.path.join(model_path,uid +'_options.json')
options = json.load(open(options_path,'r'))
print options
predictions = AugerML(options).predict_by_model(uid,model_path,test_path)
print predictions

**Comment by skatedplrn** [comment]
you do not need to load options, just use empty dict
predict_by_model return path to the csv file with predicted data
