### ISSUE TITLE
Regression leaderboard returns negative numbers for scoring

### ISSUE THREAD

**Issue by knobotz** [deeplearninc/auger-ml#112]
Moved over from deeplearninc/hub#602:

I've tried R^2 and neg mean and I get negative numbers returned in leaderboard which don't make sense. 

<img width="1192" alt="screen shot 2018-04-03 at 12 17 28 pm" src="https://user-images.githubusercontent.com/30329594/38270783-4fe8aeb4-3739-11e8-8a7f-fdd39f3e248a.png">

/cc @derekflint

**Comment by derekflint** [comment]
I still see negative number returned. Isn't this an issue?
