### ISSUE TITLE
Move metrics and chart calculations to celery jobs instead of notebook

### ISSUE THREAD

**Issue by derekflint** [deeplearninc/auger-ml#123]
Long running chart calculations should be moved to celery tasks so they don't timeout.

Let's call each tab calculation individually in parallel

**Comment by skatedplrn** [comment]
Also get rid of redis, use files generated after evaluation

**Comment by derekflint** [comment]
We might want to cache metric results in redis however.  UI will poll endpoint in jupyter which will look in redis and if empty will trigger celery job.  We could store object with state and results in redis as opposed to another file.  just an idea.

**Comment by derekflint** [comment]
jupyter server actually crashes currently when this times out and does not recover.

**Comment by skatedplrn** [comment]
remove Dockerfile.basepython after that
