### ISSUE TITLE
worker unrecoverable crash building ensemble

### ISSUE THREAD

**Issue by derekflint** [deeplearninc/auger-ml#125]
Running dataset with 10 trials

https://s3-us-west-2.amazonaws.com/auger-experiments/datasets/examples/trainf7_1.2.csv

WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).
auger-ml-trials-worker_1      | [2018-05-07 18:30:18,418: INFO/MainProcess] Received task: auger_ml.trials.trials_tasks.trial_execute_task[8adc4f4e-3425-4d04-8b74-272c8d0fc686]
auger-ml-optimizers-worker_1  | [2018-05-07 18:30:18,482: ERROR/ForkPoolWorker-13] evaluate_optimizer failed.
auger-ml-optimizers-worker_1  | Traceback (most recent call last):
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/optimizers/AugerMLOptimizers.py", line 240, in evaluate_optimizer_algorithm
auger-ml-optimizers-worker_1  |     return optimizer.evaluate_algorithm(params['algorithm_name'], params['algorithm_params'])
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/ensembles/algorithms.py", line 48, in evaluate_algorithm
auger-ml-optimizers-worker_1  |     return self.execute_trial(algo_name, **algo_params)['result']
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/ensembles/algorithms.py", line 26, in execute_trial
auger-ml-optimizers-worker_1  |     return self.trialsQueue.execute_trial(trial)
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/trials/trials_queue.py", line 13, in execute_trial
auger-ml-optimizers-worker_1  |     return self.execute_trials([trial])[0]
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/trials/trials_queue.py", line 10, in execute_trials
auger-ml-optimizers-worker_1  |     return self._execute_tasks(trials, trial_execute_task)
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/base_tasks_queue.py", line 87, in _execute_tasks
auger-ml-optimizers-worker_1  |     timeout=self.options.get('queue_poll_sec', 20))
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/result.py", line 749, in join_native
auger-ml-optimizers-worker_1  |     raise value
auger-ml-optimizers-worker_1  | WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).
auger-ml-optimizers-worker_1  | [2018-05-07 18:30:18,648: INFO/ForkPoolWorker-13] Task auger_ml.optimizers.optimizers_tasks.optimizer_algorithm_task[102c0839-7594-417d-83a9-f47ea117fa37] succeeded in 199.2132891s: -inf

**Comment by knobotz** [comment]
@derekflint does the worker restart automatically? If not then it should be a [bug in the helm-repo repository](https://github.com/deeplearninc/helm-repo/issues/new), because the worker is set to [restart automatically there](https://github.com/deeplearninc/helm-repo/blob/experimental/auger-project/templates/augerml/optimizers-worker.yaml#L36).

**Comment by derekflint** [comment]
@knobotz i was running locally, it looked like it didn't restart or update job status so it kept in state 'started' w/o updates

**Comment by skatedplrn** [comment]
did you use timestamp type for click_time and attributed_time?

**Comment by derekflint** [comment]
@skatedplrn I only used click_time as a feature and set it to timestamp

**Comment by knobotz** [comment]
>@knobotz i was running locally, it looked like it didn't restart or update job status so it kept in state 'started' w/o updates

The restart behavior can be tested locally via docker by setting the [`restart_policy`](https://docs.docker.com/compose/compose-file/#restart_policy) in `docker-compose.yml`.

**Comment by derekflint** [comment]
Other issue is if it does crash it should gracefully stop trial and change status so UI does not hang.

**Comment by skatedplrn** [comment]
Now it stops gracefully,
On cluster it works just fine
