### ISSUE TITLE
Feature importance tab on metric displays incorrect value

### ISSUE THREAD

**Issue by derekflint** [deeplearninc/auger-ml#130]
Running bike dataset regression.  Looking at metrics for model row the feature importance tab shows large values when it should be percentage of 1.

<img width="1077" alt="screen shot 2018-05-10 at 9 39 44 am" src="https://user-images.githubusercontent.com/30329594/39881793-cfe79f16-5436-11e8-9299-8d4b69ba6165.png">

**Comment by skatedplrn** [comment]
https://github.com/deeplearninc/auger-notebook/blob/pandas_data_source/auger_notebook/models/regression/metrics.py#L347

**Comment by skatedplrn** [comment]
Now it show correct values, strange

**Comment by StanislavVolodarskiy** [comment]
I've got conversation with Vladislav, Denis and Alexander fishkow. The common opinion is that feature importance range and meaning depends on algorithm. It's normal for some algorithms two show feature importances far out of [-1, 1] range.
I'd suggest to change scale on left side from fixed [-1, 1] to variable scale depending on actual feature importances.
OR we can normalize feature importances before rendering.
@derekflint , I need your opinion.

**Comment by derekflint** [comment]
Let’s just normalize values so they are always percentage of 1

**Comment by StanislavVolodarskiy** [comment]
Fixed: https://github.com/deeplearninc/auger-notebook/commit/00a0ff12bf04080f050b06f854b19f84e0a259af.
