### ISSUE TITLE
Adult dataset ROC curve looks strange

### ISSUE THREAD

**Issue by derekflint** [deeplearninc/auger-ml#131]
Normally the curve moves along the x-axis. maybe there are some missing values?

<img width="1098" alt="screen shot 2018-05-10 at 9 49 58 am" src="https://user-images.githubusercontent.com/30329594/39882059-9b69d528-5437-11e8-9abd-d0fa9d73b213.png">

**Comment by skatedplrn** [comment]
https://github.com/deeplearninc/auger-notebook/blob/pandas_data_source/auger_notebook/models/regression/metrics.py#L309

**Comment by StanislavVolodarskiy** [comment]
Fixed https://github.com/deeplearninc/auger-notebook/commit/e1935b2d9bba7ba696308df68ba8c1bcccbf71de. @derekflint , please check it.
