### ISSUE TITLE
Create redis spark-streaming-context to process model evaluation data

### ISSUE THREAD

**Issue by knobotz** [deeplearninc/auger-ml#14]
Remove model evaluation processing from the jupyter process and create a spark streaming context in the spark jobserver. The streaming context would connect to redis and process model evaluation data as it is sent to redis:

https://spark.apache.org/docs/latest/streaming-programming-guide.html#dataframe-and-sql-operations

https://github.com/RedisLabs/spark-redis#streaming

**Comment by skatedplrn** [comment]
We can also use this library to access local filesystem or S3 
https://github.com/apache/libcloud
