### ISSUE TITLE
Regression search space seems to be persisted even if classification model created

### ISSUE THREAD

**Issue by derekflint** [deeplearninc/auger-ml#148]
To repro on prod:

1) Create auger-notebook for bike sharing dataset
2) Run notebook and see leaderboard displays correct regression scoring and algorithms
3) Create auger-notebook for iris dataset
4) Run notebook and see regression algorithms are used and scoring is regression.

I looked in notebook at local config set and it looks like classification details are present. Something on auger-ml must be using old params? not sure.

**Comment by skatedplrn** [comment]
I see such effect only for 1-2 sec, just after I press run and leaderboard appear, for some reason it displays previous leaderboard, looks like UI issue to me

**Comment by derekflint** [comment]
I see this issue now too, maybe i was running an older version. I'll assign to @mha23
