### ISSUE TITLE
Jupyter kernel crashes for medium size dataset on data preprocessing steps

### ISSUE THREAD

**Issue by derekflint** [deeplearninc/auger-ml#168]
https://s3-us-west-2.amazonaws.com/auger-experiments/datasets/examples/sales_train.csv

Try loading this dataset either locally or with xlarge cluster.  It hits cpu limits during data preprocessing steps(not sure exactly cause I can't get stack trace).  This is a medium size dataset IMO.  

We need to be able to recover from cpu/memory limits in jupyter process. Please look into potentially moving operation that causes crash to celery job.

**Comment by derekflint** [comment]
@skatedplrn , not seeing this anymore on cluster, maybe it was fixed or something else caused it.

**Comment by skatedplrn** [comment]
This is issue with datetime field: date
without it, preprocessors works fine,

I fixed one issue inside DateTimePreprocessor, but it still stopped in other preprocessors
If I keep only DateTimePreprocessor, it finished fine in 2 GB docker
