### ISSUE TITLE
REDO get_top_pipelines

### ISSUE THREAD

**Issue by 4SkyNet** [deeplearninc/auger-ml#171]
get_top_pipelines should return:
+ one best model for each algorithm
+ 2 best models (in addition to previous)

**Comment by StanislavVolodarskiy** [comment]
Fixed.

**Comment by 4SkyNet** [comment]
Closed by https://github.com/deeplearninc/auger-ml/commit/7d0349dc06ef65021b2f6bc4b7bffec7057c631e

P.S> needs to transfer these changes to the `default` branch
