### ISSUE TITLE
Exceptions encountered during data load do not send feedback to UI

### ISSUE THREAD

**Issue by derekflint** [deeplearninc/auger-ml#180]
I was uploading a dataset(https://s3-us-west-2.amazonaws.com/auger-experiments/datasets/examples/donor.csv) and it appears there is parsing error.  The UI does not get any feedback on failures from celery task.  We should display exception.

logs below:

[2018-06-01 17:45:36,243: INFO/MainProcess] Received task: auger_ml.optimizers.optimizers_tasks.datasource_task[9c6dba44-4b18-49fc-9bb9-be766e7f9bde]
auger-ml-optimizers-worker_1  | [2018-06-01 17:45:36,291: ERROR/ForkPoolWorker-10] Task auger_ml.optimizers.optimizers_tasks.datasource_task[9c6dba44-4b18-49fc-9bb9-be766e7f9bde] raised unexpected: ParserError('Error tokenizing data. C error: Expected 18 fields in line 3, saw 19\n',)
auger-ml-optimizers-worker_1  | Traceback (most recent call last):
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 375, in trace_task
auger-ml-optimizers-worker_1  |     R = retval = fun(*args, **kwargs)
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 632, in __protected_call__
auger-ml-optimizers-worker_1  |     return self.run(*args, **kwargs)
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/optimizers/optimizers_tasks.py", line 66, in datasource_task
auger-ml-optimizers-worker_1  |     ds.load()
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/data_source/data_source_api.py", line 27, in load
auger-ml-optimizers-worker_1  |     self.run_ds_method("load", features, use_cache)
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/data_source/data_source_api.py", line 133, in run_ds_method
auger-ml-optimizers-worker_1  |     result = result(*args)
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/data_source/data_source_api_pandas.py", line 53, in load
auger-ml-optimizers-worker_1  |     self.df = pd.read_csv(path, parse_dates=self.options.get("datetimeFeatures", False), encoding='utf-8', escapechar="\\", usecols = features)
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 678, in parser_f
auger-ml-optimizers-worker_1  |     return _read(filepath_or_buffer, kwds)
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 446, in _read
auger-ml-optimizers-worker_1  |     data = parser.read(nrows)
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1036, in read
auger-ml-optimizers-worker_1  |     ret = self._engine.read(nrows)
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1848, in read
auger-ml-optimizers-worker_1  |     data = self._reader.read(nrows)
auger-ml-optimizers-worker_1  |   File "pandas/_libs/parsers.pyx", line 876, in pandas._libs.parsers.TextReader.read
auger-ml-optimizers-worker_1  |   File "pandas/_libs/parsers.pyx", line 891, in pandas._libs.parsers.TextReader._read_low_memory
auger-ml-optimizers-worker_1  |   File "pandas/_libs/parsers.pyx", line 945, in pandas._libs.parsers.TextReader._read_rows

**Comment by derekflint** [comment]
@skatedplrn seeing same thing with failures in optimizer tasks. No feedback to UI

,604: ERROR/ForkPoolWorker-9] Task auger_ml.optimizers.optimizers_tasks.datasource_task[b8c96a2f-29f4-4c56-9406-a1cf58cf7c2f] raised unexpected: ValueError("invalid literal for long() with base 10: 'c8e40d76c14dbc404075f9013d5cd166'",)
auger-ml-optimizers-worker_1  | Traceback (most recent call last):
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 375, in trace_task
auger-ml-optimizers-worker_1  |     R = retval = fun(*args, **kwargs)
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 632, in __protected_call__
auger-ml-optimizers-worker_1  |     return self.run(*args, **kwargs)
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/optimizers/optimizers_tasks.py", line 67, in datasource_task
auger-ml-optimizers-worker_1  |     return ds.run_ds_method(params['remote_method_name'], *params['remote_method_arguments'])
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/data_source/data_source_api.py", line 133, in run_ds_method
auger-ml-optimizers-worker_1  |     result = result(*args)
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/data_source/data_source_api_pandas.py", line 568, in transform
auger-ml-optimizers-worker_1  |     getattr(self, name)(**args)
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/data_source/data_source_api_pandas.py", line 370, in withNumericColumn
auger-ml-optimizers-worker_1  |     self.df[col_name] = self.df[col_name].astype(int)
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/dist-packages/pandas/util/_decorators.py", line 177, in wrapper

**Comment by derekflint** [comment]
here is my dataset for testing https://s3-us-west-2.amazonaws.com/auger-experiments/datasets/examples/donor.csv

**Comment by skatedplrn** [comment]
Please update experimental branch of auger-ml, now exceptions passed to evaluate_model
Evaluate stopped, but error is not displayed. This code:
            logging.exception(e)
            self.table.evaluate_output = [{'evaluation_status': 'error'}]

            self.alertWidget.alert("danger", str(e))
            self.table.run_spin = uuid.uuid4().hex[:6].upper()

Does not update error, or may be it is hidden under Preparing message

**Comment by skatedplrn** [comment]
If categorical or datetime preprocessor failed, process should stop
Each preprocessor in case of exception should add error to errors hash:
errors[name] = error
and after preprocessors finished, errors should be written to status
