### ISSUE TITLE
predict_by_model fails for ensemble model

### ISSUE THREAD

**Issue by knobotz** [deeplearninc/auger-ml#216]
Moved over from https://github.com/deeplearninc/hub/issues/803. 

Steps to reproduce:

1. Run bike daily dataset
2. Deploy an ensemble model
3. Go to the test UI page for the model and try to run it, you will get:

```json
{
  "error": "too many indices for array"
}
```

Other non-ensemble models for the same project run work fine.

**Comment by skatedplrn** [comment]
Issue is with ensemle predict
