### ISSUE TITLE
Ensemble exception with MLPClassifier

### ISSUE THREAD

**Issue by skatedplrn** [deeplearninc/auger-ml#260]
Reproduced once with adult dataset:
[2018-08-06 18:26:11,741: ERROR/ForkPoolWorker-1] Error while evaluating pipeline: AveragingAlgorithm(_steps_params=None, classification=True, n_best=3,
auger-ml-trials-worker_1      |           weights=None)
auger-ml-trials-worker_1      | Traceback (most recent call last):
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/trials/AugerMLTrial.py", line 114, in _evaluate_model
auger-ml-trials-worker_1      |     self._do_evaluate_model(model)
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/trials/AugerMLTrial.py", line 155, in _do_evaluate_model
auger-ml-trials-worker_1      |     self.trial['algorithm_params']
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/ensembles/algorithms.py", line 281, in build_ensemble_and_update_algorithm_params
auger-ml-trials-worker_1      |     score, pipelines = selector.select()
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/ensembles/build.py", line 55, in select
auger-ml-trials-worker_1      |     score = self._calc_scores(preds)
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/ensembles/build.py", line 72, in _calc_scores
auger-ml-trials-worker_1      |     y_pred += np.eye(n_classes)[pred.reshape(-1)]   # one_hot
auger-ml-trials-worker_1      | IndexError: arrays used as indices must be of integer (or boolean) type
auger-ml-trials-worker_1      | [2018-08-06 18:26:11,775: ERROR/ForkPoolWorker-2] Error while evaluating pipeline: GreedySelectionAlgorithm(_steps_params=None, bag_fraction=0.5,
auger-ml-trials-worker_1      |              improve_eps=False, max_bag_pipelines=3, n_bags=3, n_best=1,
auger-ml-trials-worker_1      |              prune_fraction=0.0, random_state=12345)
auger-ml-trials-worker_1      | Traceback (most recent call last):
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/trials/AugerMLTrial.py", line 114, in _evaluate_model
auger-ml-trials-worker_1      |     self._do_evaluate_model(model)
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/trials/AugerMLTrial.py", line 155, in _do_evaluate_model
auger-ml-trials-worker_1      |     self.trial['algorithm_params']
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/ensembles/algorithms.py", line 187, in build_ensemble_and_update_algorithm_params
auger-ml-trials-worker_1      |     score, params = ens.build()
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/ensembles/greedy_selection.py", line 83, in build
auger-ml-trials-worker_1      |     score, weights, ensemble_probs = self._get_score_and_weights()
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/ensembles/greedy_selection.py", line 108, in _get_score_and_weights
auger-ml-trials-worker_1      |     ensemble_probs += np.asarray(self._predictions[idx]['y_predicted_proba']) * weight
auger-ml-trials-worker_1      | TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
auger-ml-trials-worker_1      | [2018-08-06 18:26:11,791: ERROR/ForkPoolWorker-3] Error while evaluating pipeline: VotingAlgorithm(_steps_params=None, n_best=3, voting=u'soft', weights=None)
auger-ml-trials-worker_1      | Traceback (most recent call last):
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/trials/AugerMLTrial.py", line 114, in _evaluate_model
auger-ml-trials-worker_1      |     self._do_evaluate_model(model)
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/trials/AugerMLTrial.py", line 155, in _do_evaluate_model
auger-ml-trials-worker_1      |     self.trial['algorithm_params']
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/ensembles/algorithms.py", line 231, in build_ensemble_and_update_algorithm_params
auger-ml-trials-worker_1      |     score, pipelines = selector.select()
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/ensembles/build.py", line 55, in select
auger-ml-trials-worker_1      |     score = self._calc_scores(preds)
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/dist-packages/auger_ml/ensembles/build.py", line 72, in _calc_scores
auger-ml-trials-worker_1      |     y_pred += np.eye(n_classes)[pred.reshape(-1)]   # one_hot
auger-ml-trials-worker_1      | IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by 4SkyNet** [comment]
outdated
