### ISSUE TITLE
DNN3 classifier w/ credit dataset

### ISSUE THREAD

**Issue by knobotz** [deeplearninc/auger-ml#267]
Feel free to close if it's invalid, but just using default settings, set k-fold to 10, the DNN3 classifier results aren't very good. The DNN2 classifier appears to work better.

<img width="1137" alt="screen shot 2018-08-09 at 11 09 01 am" src="https://user-images.githubusercontent.com/30328334/43917421-28b3fbd2-9bc5-11e8-8625-3c3af7a7e541.png">
<img width="1128" alt="screen shot 2018-08-09 at 11 09 15 am" src="https://user-images.githubusercontent.com/30328334/43917423-28d38dda-9bc5-11e8-9f89-305f58680952.png">

**Comment by jetsnguns** [comment]
This should not be the case for all data sets, but it may happen. I'm closing this for now.
