### ISSUE TITLE
Add stacking algorithm to top of pipelines

### ISSUE THREAD

**Issue by skatedplrn** [deeplearninc/auger-ml#28]
Let's use source code from here:
http://rasbt.github.io/mlxtend/api_subpackages/mlxtend.classifier/

https://github.com/rushter/heamy
https://github.com/kaz-Anova/StackNet

[ensemble whitepaper](https://docs.google.com/document/d/1wu_1PwGmGdjN12gy--lzpqHqBc7sER4xEsmDBOyxsMU)

**Comment by 4SkyNet** [comment]
We also need to collect / store out model's predictions to perform ensemble building automatically & with some meta-learner

**Comment by 4SkyNet** [comment]
`Stacking` is eliminated by current optimizers for now
-> `stacking` can be added later to the existing ensembles,
(since it weaker and prone to over-fitting)
