### ISSUE TITLE
Timeseries models

### ISSUE THREAD

**Issue by skatedplrn** [deeplearninc/auger-ml#320]
Enumerate which models can be used for TS

**Comment by khizanov** [comment]
For trending data the following algorithms should be used:
 * ElasticNet
 * LassoLars
 * Ridge
 * LinearSVR
 * SVR
 * MLPRegressor
 * DeepNeuralNetworkRegressor

However, for data without strict trend any algorithm can be applied.

**Comment by khizanov** [comment]
All metrics can be used for this task. For trending data 'explained_variance' and 'r2' may provide too high scores, which might be hard to compare.
