### ISSUE TITLE
Hub: pass trial metrics to hub backend

### ISSUE THREAD

**Issue by timashev** [deeplearninc/auger-ml#337]
For this: https://github.com/deeplearninc/hub/issues/868

At this moment we have `raw_data` for each trial, but it does not contain `metrics` which required to draw charts in Leaderboard.

(See mocked JavaScript objects for UI tests: https://github.com/deeplearninc/hub/blob/master/.storybook/mocks/trials.js#L428 and https://github.com/deeplearninc/hub/blob/master/.storybook/mocks/trials.js#L493 for example)

On Hub `raw_data` contains a lot of things (like `all_scores`, `algorithm_params`, `featureColumns`, etc), but not `metrics` that we need for the Leaderboard charts.

**Comment by mha23** [comment]
To get this information we need to call augerML evaluation process. It takes time
the process should be call api, then wait for ws updates then use information for metrics
Now we are doing this flow in auger-notebook

**Comment by skatedplrn** [comment]
User has to call View metrics on specific trial, then this information will be added to trial:
https://app-staging.auger.ai/admin/trials/1920371

**Comment by skatedplrn** [comment]
User has to call View metrics on specific trial, then this information will be added to trial:
https://app-staging.auger.ai/admin/trials/1920371
