### ISSUE TITLE
PCA preprocessor generate columns with null values

### ISSUE THREAD

**Issue by skatedplrn** [deeplearninc/auger-ml#343]
Reproduced on customer dataset (1GB)
PCA remove a lot of columns and add pca__xxx, which contains nulls
Also it change non-removed fields and add nulls there

If no PCA used:
{'count': 6153314, 'dtypes': [(u'geo__us', 'int'), (u'geo__gb', 'int'), (u'geo__ca', 'int'), (u'geo__au', 'int'), (u'geo__xx', 'int'), (u'geo__nolocation', 'int'), (u'geo__za', 'int'), (u'geo__nz', 'int'), (u'geo__ie', 'int'), (u'geo__sg', 'int'), (u'geo__my', 'int'), (u'geo__hk', 'int'), (u'geo__il', 'int'), (u'geo__pr', 'int'), (u'geo__in', 'int'), (u'geo__bs', 'int'), (u'geo__ph', 'int'), (u'geo__mx', 'int'), (u'geo__tr', 'int'), (u'geo__qa', 'int'), (u'geo__undefined', 'int'), (u'geo__ky', 'int'), (u'geo__th', 'int'), (u'geo__br', 'int'), (u'geo__gr', 'int'), (u'geo__id', 'int'), (u'geo__ru', 'int'), (u'geo__kr', 'int'), (u'geo__es', 'int'), (u'geo__cy', 'int'), (u'geo__is', 'int'), (u'geo__pt', 'int'), (u'geo__vi', 'int'), (u'geo__se', 'int'), (u'geo__ch', 'int'), (u'geo__jp', 'int'), (u'geo__gu', 'int'), (u'geo__ng', 'int'), (u'geo__de', 'int'), (u'geo__bm', 'int'), (u'geo__pl', 'int'), (u'geo__nl', 'int'), (u'geo__jm', 'int'), (u'geo__je', 'int'), (u'geo__hr', 'int'), (u'geo__gg', 'int'), (u'geo__ua', 'int'), (u'geo__aw', 'int'), (u'geo__tt', 'int'), (u'geo__fr', 'int'), (u'geo__BUCKET_CATEGORY', 'int'), (u'current_click_value', 'double')], 'stat_data': [{'orig_column_name': 'geo__us', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__us', 'missing_values': 0}, {'orig_column_name': 'geo__gb', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__gb', 'missing_values': 0}, {'orig_column_name': 'geo__ca', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__ca', 'missing_values': 0}, {'orig_column_name': 'geo__au', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__au', 'missing_values': 0}, {'orig_column_name': 'geo__xx', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__xx', 'missing_values': 0}, {'orig_column_name': 'geo__nolocation', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__nolocation', 'missing_values': 0}, {'orig_column_name': 'geo__za', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__za', 'missing_values': 0}, {'orig_column_name': 'geo__nz', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__nz', 'missing_values': 0}, {'orig_column_name': 'geo__ie', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__ie', 'missing_values': 0}, {'orig_column_name': 'geo__sg', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__sg', 'missing_values': 0}, {'orig_column_name': 'geo__my', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__my', 'missing_values': 0}, {'orig_column_name': 'geo__hk', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__hk', 'missing_values': 0}, {'orig_column_name': 'geo__il', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__il', 'missing_values': 0}, {'orig_column_name': 'geo__pr', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__pr', 'missing_values': 0}, {'orig_column_name': 'geo__in', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__in', 'missing_values': 0}, {'orig_column_name': 'geo__bs', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__bs', 'missing_values': 0}, {'orig_column_name': 'geo__ph', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__ph', 'missing_values': 0}, {'orig_column_name': 'geo__mx', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__mx', 'missing_values': 0}, {'orig_column_name': 'geo__tr', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__tr', 'missing_values': 0}, {'orig_column_name': 'geo__qa', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__qa', 'missing_values': 0}, {'orig_column_name': 'geo__undefined', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__undefined', 'missing_values': 0}, {'orig_column_name': 'geo__ky', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__ky', 'missing_values': 0}, {'orig_column_name': 'geo__th', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__th', 'missing_values': 0}, {'orig_column_name': 'geo__br', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__br', 'missing_values': 0}, {'orig_column_name': 'geo__gr', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__gr', 'missing_values': 0}, {'orig_column_name': 'geo__id', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__id', 'missing_values': 0}, {'orig_column_name': 'geo__ru', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__ru', 'missing_values': 0}, {'orig_column_name': 'geo__kr', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__kr', 'missing_values': 0}, {'orig_column_name': 'geo__es', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__es', 'missing_values': 0}, {'orig_column_name': 'geo__cy', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__cy', 'missing_values': 0}, {'orig_column_name': 'geo__is', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__is', 'missing_values': 0}, {'orig_column_name': 'geo__pt', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__pt', 'missing_values': 0}, {'orig_column_name': 'geo__vi', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__vi', 'missing_values': 0}, {'orig_column_name': 'geo__se', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__se', 'missing_values': 0}, {'orig_column_name': 'geo__ch', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__ch', 'missing_values': 0}, {'orig_column_name': 'geo__jp', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__jp', 'missing_values': 0}, {'orig_column_name': 'geo__gu', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__gu', 'missing_values': 0}, {'orig_column_name': 'geo__ng', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__ng', 'missing_values': 0}, {'orig_column_name': 'geo__de', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__de', 'missing_values': 0}, {'orig_column_name': 'geo__bm', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__bm', 'missing_values': 0}, {'orig_column_name': 'geo__pl', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__pl', 'missing_values': 0}, {'orig_column_name': 'geo__nl', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__nl', 'missing_values': 0}, {'orig_column_name': 'geo__jm', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__jm', 'missing_values': 0}, {'orig_column_name': 'geo__je', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__je', 'missing_values': 0}, {'orig_column_name': 'geo__hr', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__hr', 'missing_values': 0}, {'orig_column_name': 'geo__gg', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__gg', 'missing_values': 0}, {'orig_column_name': 'geo__ua', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__ua', 'missing_values': 0}, {'orig_column_name': 'geo__aw', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__aw', 'missing_values': 0}, {'orig_column_name': 'geo__tt', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__tt', 'missing_values': 0}, {'orig_column_name': 'geo__fr', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__fr', 'missing_values': 0}, {'orig_column_name': 'geo__BUCKET_CATEGORY', 'isTarget': False, 'parent': False, 'orig_datatype': 'int', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'int', 'range': ('', ''), 'column_name': 'geo__BUCKET_CATEGORY', 'missing_values': 0}, {'orig_column_name': 'current_click_value', 'isTarget': False, 'parent': False, 'orig_datatype': 'double', 'child': '', 'use': False, 'unique_values': 173, 'datatype': 'double', 'range': ('', ''), 'column_name': 'current_click_value', 'missing_values': 0}], 'columns': [u'geo__us', u'geo__gb', u'geo__ca', u'geo__au', u'geo__xx', u'geo__nolocation', u'geo__za', u'geo__nz', u'geo__ie', u'geo__sg', u'geo__my', u'geo__hk', u'geo__il', u'geo__pr', u'geo__in', u'geo__bs', u'geo__ph', u'geo__mx', u'geo__tr', u'geo__qa', u'geo__undefined', u'geo__ky', u'geo__th', u'geo__br', u'geo__gr', u'geo__id', u'geo__ru', u'geo__kr', u'geo__es', u'geo__cy', u'geo__is', u'geo__pt', u'geo__vi', u'geo__se', u'geo__ch', u'geo__jp', u'geo__gu', u'geo__ng', u'geo__de', u'geo__bm', u'geo__pl', u'geo__nl', u'geo__jm', u'geo__je', u'geo__hr', u'geo__gg', u'geo__ua', u'geo__aw', u'geo__tt', u'geo__fr', u'geo__BUCKET_CATEGORY', u'current_click_value']}

With PCA:
{'count': 6153783, 'dtypes': [(u'geo__us', 'double'), (u'geo__gb', 'double'), (u'geo__ca', 'double'), (u'pca_0', 'double'), (u'pca_1', 'double'), (u'pca_2', 'double'), (u'pca_3', 'double'), (u'pca_4', 'double'), (u'pca_5', 'double'), (u'pca_6', 'double'), (u'pca_7', 'double'), (u'pca_8', 'double'), (u'current_click_value', 'double')], 'stat_data': [{'orig_column_name': 'geo__us', 'isTarget': False, 'parent': False, 'orig_datatype': 'double', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'double', 'range': ('', ''), 'column_name': 'geo__us', 'missing_values': 469}, {'orig_column_name': 'geo__gb', 'isTarget': False, 'parent': False, 'orig_datatype': 'double', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'double', 'range': ('', ''), 'column_name': 'geo__gb', 'missing_values': 469}, {'orig_column_name': 'geo__ca', 'isTarget': False, 'parent': False, 'orig_datatype': 'double', 'child': '', 'use': False, 'unique_values': 2, 'datatype': 'double', 'range': ('', ''), 'column_name': 'geo__ca', 'missing_values': 469}, {'orig_column_name': 'pca_0', 'isTarget': False, 'parent': False, 'orig_datatype': 'double', 'child': '', 'use': False, 'unique_values': 49, 'datatype': 'double', 'range': ('', ''), 'column_name': 'pca_0', 'missing_values': 469}, {'orig_column_name': 'pca_1', 'isTarget': False, 'parent': False, 'orig_datatype': 'double', 'child': '', 'use': False, 'unique_values': 49, 'datatype': 'double', 'range': ('', ''), 'column_name': 'pca_1', 'missing_values': 469}, {'orig_column_name': 'pca_2', 'isTarget': False, 'parent': False, 'orig_datatype': 'double', 'child': '', 'use': False, 'unique_values': 49, 'datatype': 'double', 'range': ('', ''), 'column_name': 'pca_2', 'missing_values': 469}, {'orig_column_name': 'pca_3', 'isTarget': False, 'parent': False, 'orig_datatype': 'double', 'child': '', 'use': False, 'unique_values': 49, 'datatype': 'double', 'range': ('', ''), 'column_name': 'pca_3', 'missing_values': 469}, {'orig_column_name': 'pca_4', 'isTarget': False, 'parent': False, 'orig_datatype': 'double', 'child': '', 'use': False, 'unique_values': 49, 'datatype': 'double', 'range': ('', ''), 'column_name': 'pca_4', 'missing_values': 469}, {'orig_column_name': 'pca_5', 'isTarget': False, 'parent': False, 'orig_datatype': 'double', 'child': '', 'use': False, 'unique_values': 49, 'datatype': 'double', 'range': ('', ''), 'column_name': 'pca_5', 'missing_values': 469}, {'orig_column_name': 'pca_6', 'isTarget': False, 'parent': False, 'orig_datatype': 'double', 'child': '', 'use': False, 'unique_values': 49, 'datatype': 'double', 'range': ('', ''), 'column_name': 'pca_6', 'missing_values': 469}, {'orig_column_name': 'pca_7', 'isTarget': False, 'parent': False, 'orig_datatype': 'double', 'child': '', 'use': False, 'unique_values': 49, 'datatype': 'double', 'range': ('', ''), 'column_name': 'pca_7', 'missing_values': 469}, {'orig_column_name': 'pca_8', 'isTarget': False, 'parent': False, 'orig_datatype': 'double', 'child': '', 'use': False, 'unique_values': 49, 'datatype': 'double', 'range': ('', ''), 'column_name': 'pca_8', 'missing_values': 469}, {'orig_column_name': 'current_click_value', 'isTarget': False, 'parent': False, 'orig_datatype': 'double', 'child': '', 'use': False, 'unique_values': 173, 'datatype': 'double', 'range': ('', ''), 'column_name': 'current_click_value', 'missing_values': 0}], 'columns': [u'geo__us', u'geo__gb', u'geo__ca', u'pca_0', u'pca_1', u'pca_2', u'pca_3', u'pca_4', u'pca_5', u'pca_6', u'pca_7', u'pca_8', u'current_click_value']}

**Comment by skatedplrn** [comment]
https://github.com/deeplearninc/auger-ml/pull/345

edit and uncomment geo field:
test_auger_ml_optimizers.py: line 100 and 102:
options['featureColumns'] = ["os_family","browser_family","device","timestamp", "depth","geo"]
options['categoricalFeatures'] = ["os_family","browser_family","device","geo"]

run:
 pytest -s ./tests/test_auger_ml_optimizers.py::TestAugerMLOptimizers::test_customer_data

if commented SparsePreprocessor:
https://github.com/deeplearninc/auger-ml/blob/experimental/auger_ml/optimizers/AugerMLOptimizers.py#L95

It works again

**Comment by skatedplrn** [comment]
Scale preprocessor issue:
pytest -s ./tests/test_auger_ml_optimizers.py::TestAugerMLOptimizers::test_regression_customer_data

**Comment by khizanov** [comment]
The issue caused by NaN preprocessor. Fixed in 2924efd
