### ISSUE TITLE
load datasource task does not return exceptions to calling function

### ISSUE THREAD

**Issue by derekflint** [deeplearninc/auger-ml#380]
res = AugerMLProxy(self.ds_options).callDSTask("getStatistics", None)

I am loading a bad gz file which uploads successfully and then UI calls DSTask which fails in pandas load. Exception is never returned to UI to display error and clean up loader

auger-ml-trials-worker-4_1    |   File "pandas/_libs/parsers.pyx", line 2101, in pandas._libs.parsers.raise_parser_error
auger-ml-trials-worker-4_1    | IOError: Not a gzipped file

**Comment by skatedplrn** [comment]
This is issue with auger notebook, how it handles exceptions.
AugerMLProxy(self.ds_options).callDSTask("getStatistics", None) raise exception, but notebook does not display it.

Try to add raise to collect_dataframe and see:

    def collect_dataframe(self):
        raise Exception("Test error")
