### ISSUE TITLE
Support function that takes csv file and returns predictions

### ISSUE THREAD

**Issue by derekflint** [deeplearninc/auger-ml#387]
Customer feedback. would like to upload a csv of test data to get predictions. 

Add function to load into pandas and return predictions. I'll add file upload capability.

**Comment by knobotz** [comment]
Can probably be handled in the browser (csv parsed and converted to JSON request). Since we only support 200 rows per prediction request.

**Comment by skatedplrn** [comment]
def predict_by_model(self, model_path, path_to_predict=None, records=None, features=None, predict_value_num=None):
