### ISSUE TITLE
Test failed test_ensembles_algorithms_compatibility['auger_ml.algorithms.dnn.DeepNeuralNetworkClassifier']

### ISSUE THREAD

**Issue by skatedplrn** [deeplearninc/auger-ml#433]
1. turn on slow specs:
tests/utils.py:
def is_run_slow_specs():
    return True #os.environ.get('INCLUDE_SLOW_SPECS')
2. edit test_auger_ml_ensembles.py
@pytest.mark.parametrize('classifier', ['auger_ml.algorithms.dnn.DeepNeuralNetworkClassifier'])
    def test_ensembles_algorithms_compatibility(self, classifier):

3. Run:
pytest -s ./tests/test_auger_ml_ensembles.py::TestAugerMLEnsembles::test_ensembles_algorithms_compatibility
    
See:
=================================== FAILURES ===================================
 TestAugerMLEnsembles.test_ensembles_algorithms_compatibility[auger_ml.algorithms.dnn.DeepNeuralNetworkClassifier] 

self = <tests.test_auger_ml_ensembles.TestAugerMLEnsembles object at 0x7f84f91d0890>
classifier = 'auger_ml.algorithms.dnn.DeepNeuralNetworkClassifier'

    @pytest.mark.parametrize('classifier', ['auger_ml.algorithms.dnn.DeepNeuralNetworkClassifier'])
    def test_ensembles_algorithms_compatibility(self, classifier):
        search_space = {classifier: classifier_space[classifier]}
    
        options = self._get_options(search_space=search_space)
        self._dump_predictions(options)
        d = load_data.load(options)
    
        status = AugerML(options).read_channel_file("evaluation_status.json")
        if 'Empty algorithm search space' in status.get('errors',{}).get('error',''):
            return
    
        algo_min_score = min(p['score'] for p in d['predictions'])
    
        selector = build.EnsembleSelection(
            self._get_options(search_space=search_space, create_project_run=False),
            load_data.load(options)
        )
        score, list_of_selected_pipelines = selector.select()
        score, params = SuperLearner(options, d).build()
        assert score > algo_min_score / 2
    
        e = Ensemble(options, **params)
        joblib.dump(e, StringIO.StringIO())
    
>       score, params = GreedySelection(options, d).build()

tests/test_auger_ml_ensembles.py:190: 
                                        
auger_ml/ensembles/greedy_selection.py:83: in build
    score, weights, ensemble_probs = self._get_score_and_weights()
                                        

self = <auger_ml.ensembles.greedy_selection.GreedySelection object at 0x7f84f7dea810>

    def _get_score_and_weights(self):
        ensemble_weights = [0] * len(self._pipelines)
        ensemble_probs = np.zeros((self._y.shape[0], self._n_classes))
    
        for idx, weight in self._ensemble.items():
            ensemble_weights[idx] = weight
>           ensemble_probs += np.asarray(self._predictions[idx]['y_predicted_proba']) * weight
E           TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

auger_ml/ensembles/greedy_selection.py:108: TypeError
experimental

**Comment by 4SkyNet** [comment]
![passed](https://user-images.githubusercontent.com/8963763/48487258-b9e91500-e82e-11e8-99c6-dc19557f5b37.png)

**Comment by 4SkyNet** [comment]
#434

**Comment by 4SkyNet** [comment]
Merged https://github.com/deeplearninc/auger-ml/pull/434
