### ISSUE TITLE
Seq optimizers should handle trial errors

### ISSUE THREAD

**Issue by skatedplrn** [deeplearninc/auger-ml#59]
In case then trial execute return:
{'error': 'Expected n_neighbors <= n_samples,  but n_samples = 96, n_neighbors = 97', 'feature_matrix': [], 'result': 'Expected n_neighbors <= n_samples,  but n_samples = 96, n_neighbors = 97', 'scores': []}

optimizer should handle it
repro on
test_evaluate_random_search
test_evaluate_nelder_mead_and_random_search_in_parallel
with all parallel mode

**Comment by skatedplrn** [comment]
Error while evaluating pipeline: KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=100, p=2,
           weights='uniform') : Expected n_neighbors <= n_samples,  but n_samples = 96, n_neighbors = 100
Trace:
Traceback (most recent call last):
  File "/Users/evgenyvovchenko/Projects/deeplearninc/auger-ml/auger_ml/trials/AugerMLTrial.py", line 117, in _evaluate_data
    score = _score(estimator, X_test1, y_test1, scorer)
  File "/usr/local/lib/python2.7/site-packages/sklearn/model_selection/_validation.py", line 528, in _score
    score = scorer(estimator, X_test, y_test)
  File "/usr/local/lib/python2.7/site-packages/sklearn/metrics/scorer.py", line 101, in __call__
    y_pred = estimator.predict(X)
  File "/usr/local/lib/python2.7/site-packages/sklearn/neighbors/classification.py", line 145, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "/usr/local/lib/python2.7/site-packages/sklearn/neighbors/base.py", line 347, in kneighbors
    (train_size, n_neighbors)
ValueError: Expected n_neighbors <= n_samples,  but n_samples = 96, n_neighbors = 100

**Comment by skatedplrn** [comment]
Error while evaluating pipeline: LinearSVC(C=0.0157205587265, class_weight=None, dual=True, fit_intercept=True,
auger-ml-trials-worker_1      |      intercept_scaling=1, loss=u'squared_hinge', max_iter=1000,
auger-ml-trials-worker_1      |      multi_class='ovr', penalty=u'l1', random_state=None,
auger-ml-trials-worker_1      |      tol=0.000136954538484, verbose=0) : Unsupported set of arguments: The combination of penalty='l1' and loss='squared_hinge' are not supported when dual=True, Parameters: penalty=u'l1', loss=u'squared_hinge', dual=True
auger-ml-trials-worker_1      | Trace:
auger-ml-trials-worker_1      | Traceback (most recent call last):
auger-ml-trials-worker_1      |   File "/var/src/auger-ml-worker/auger_ml/auger_ml/trials/AugerMLTrial.py", line 121, in _evaluate_data
auger-ml-trials-worker_1      |     estimator.fit(X_resampled, y_resampled)
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/site-packages/sklearn/svm/classes.py", line 235, in fit
auger-ml-trials-worker_1      |     self.loss, sample_weight=sample_weight)
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/site-packages/sklearn/svm/base.py", line 886, in _fit_liblinear
auger-ml-trials-worker_1      |     solver_type = _get_liblinear_solver_type(multi_class, penalty, loss, dual)
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/site-packages/sklearn/svm/base.py", line 747, in _get_liblinear_solver_type
auger-ml-trials-worker_1      |     % (error_string, penalty, loss, dual))
auger-ml-trials-worker_1      | ValueError: Unsupported set of arguments: The combination of penalty='l1' and loss='squared_hinge' are not supported when dual=True, Parameters: penalty=u'l1', loss=u'squared_hinge', dual=True

**Comment by skatedplrn** [comment]
ufunc 'subtract' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')
auger-ml-optimizers-worker_1  | [2018-03-03 14:20:24,631: WARNING/ForkPoolWorker-3] Traceback (most recent call last):
auger-ml-optimizers-worker_1  |   File "/var/src/auger-ml-worker/auger_ml/auger_ml/optimizers/seq_base_optimizer.py", line 51, in evaluate_algorithm
auger-ml-optimizers-worker_1  |     result = self.evaluate_algo(score_func, params_bound)
auger-ml-optimizers-worker_1  |   File "/var/src/auger-ml-worker/auger_ml/auger_ml/optimizers/pso_optimizer.py", line 12, in evaluate_algo
auger-ml-optimizers-worker_1  |     return pso_wrapper(score_func, algo_params, **self.optimizer_params)
auger-ml-optimizers-worker_1  |   File "/var/src/auger-ml-worker/auger_ml/auger_ml/optimizers/pso_optimizer.py", line 6, in pso_wrapper
auger-ml-optimizers-worker_1  |     return pso(f, lower, upper, swarmsize=n_start_points, omega=omega, phip=phip, phig=phig, maxiter=max_iter)[0]
auger-ml-optimizers-worker_1  |   File "/usr/local/lib/python2.7/site-packages/pyswarm/pso.py", line 70, in pso
auger-ml-optimizers-worker_1  |     vhigh = np.abs(ub - lb)
auger-ml-optimizers-worker_1  | TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')

From Python: {u'data_path': u'None', u'method': u'evaluate_optimizers', u'options': {'scoring': 'accuracy', 'search_space_ui': {'sklearn.tree.DecisionTreeClassifier': {'min_samples_split': [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'criterion': ['gini', 'entropy'], 'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'min_samples_leaf': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]}}, 'splitOptions': {'trainAll': True, 'trainRatio': 0.8, 'selectedFeatures': [u'age', u'workclass', u'fnlwgt', u'education', u'education-num', u'marital-status', u'occupation', u'capital-gain', u'capital-loss', u'hours-per-week', u'income'], 'random': True, 'randomSeed': 3}, 'classification': True, 'channelsPath': '/var/src/auger_notebook/workspace/projects/ProjDemo/channels', 'max_total_time_mins': 10, 'data_path': '/var/src/auger_notebook/workspace/projects/ProjDemo/channels/pipeline_channel_AAEF887E05E843D58690D029EC34A8A0_tmp_data_training.csv', 'modelType': u'classification', 'max_n_trials': 10, 'task_sync_call': False, 'max_eval_time_mins': 3, 'msg_info': {'host': '/var/src/auger_notebook/workspace/projects/ProjDemo/channels', 'channel': 'pipeline_channel_AAEF887E05E843D58690D029EC34A8A0'}, 'oversampling': None, 'targetFeature': u'income', 'featureColumns': [u'age', u'workclass', u'fnlwgt', u'education', u'education-num', u'marital-status', u'occupation', u'capital-gain', u'capital-loss', u'hours-per-week'], 'optimizers': {'auger_ml.optimizers.pso_optimizer.PSOOptimizer': {'phig': 0.5, 'omega': 0.5, 'n_start_points': 10, 'phip': 0.5}}, 'crossValidationFolds': 3}}

**Comment by skatedplrn** [comment]
Error while evaluating pipeline: LogisticRegression(C=2.51184417039, class_weight=None, dual=True,
auger-ml-trials-worker_1      |           fit_intercept=True, intercept_scaling=1, max_iter=100,
auger-ml-trials-worker_1      |           multi_class='ovr', n_jobs=1, penalty=u'l1', random_state=None,
auger-ml-trials-worker_1      |           solver='liblinear', tol=0.0001, verbose=0, warm_start=False) : Unsupported set of arguments: The combination of penalty='l1' and loss='logistic_regression' are not supported when dual=True, Parameters: penalty=u'l1', loss='logistic_regression', dual=True
auger-ml-trials-worker_1      | Trace:
auger-ml-trials-worker_1      | Traceback (most recent call last):
auger-ml-trials-worker_1      |   File "/var/src/auger-ml-worker/auger_ml/auger_ml/trials/AugerMLTrial.py", line 121, in _evaluate_data
auger-ml-trials-worker_1      |     estimator.fit(X_resampled, y_resampled)
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/site-packages/sklearn/linear_model/logistic.py", line 1233, in fit
auger-ml-trials-worker_1      |     sample_weight=sample_weight)
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/site-packages/sklearn/svm/base.py", line 886, in _fit_liblinear
auger-ml-trials-worker_1      |     solver_type = _get_liblinear_solver_type(multi_class, penalty, loss, dual)
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/site-packages/sklearn/svm/base.py", line 747, in _get_liblinear_solver_type
auger-ml-trials-worker_1      |     % (error_string, penalty, loss, dual))
auger-ml-trials-worker_1      | ValueError: Unsupported set of arguments: The combination of penalty='l1' and loss='logistic_regression' are not supported when dual=True, Parameters: penalty=u'l1', loss='logistic_regression', dual=True
auger-ml-trials-worker_1      | [2018-03-04 10:14:54,188: INFO/ForkPoolWorker-3] Task auger_ml.trials.trials_tasks.trial_execute_task[b6a2d4bc-ea4e-4dd9-b2d5-f5fbb07af320] succeeded in 0.121117611001s: {'error': 'Unsupported set of arguments: The combination of penalty='l1' and loss='logistic_regression' are not supported when dual=True, Parameters: penalty=u'l1', loss='logistic_regression', dual=True', 'feature_matrix': [], 'result': 'Unsupported set of arguments: The combination of penalty='l1' and loss='logistic_regression' are not supported when dual=True, Parameters: penalty=u'l1', loss='logistic_regression', dual=True', 'scores': []}

**Comment by StanislavVolodarskiy** [comment]
@skatedplrn , please review my pull request: https://github.com/deeplearninc/auger-ml/pull/61
