### ISSUE TITLE
'LinearSVC' object has no attribute 'predict_proba'

### ISSUE THREAD

**Issue by skatedplrn** [deeplearninc/auger-ml#68]
Error while evaluating pipeline: LinearSVC(C=12.7325195706, class_weight=None, dual=False, fit_intercept=True,
auger-ml-trials-worker_1      |      intercept_scaling=1, loss=u'squared_hinge', max_iter=1000,
auger-ml-trials-worker_1      |      multi_class='ovr', penalty=u'l1', random_state=None,
auger-ml-trials-worker_1      |      tol=0.00786120531625, verbose=0) : 'LinearSVC' object has no attribute 'predict_proba'
auger-ml-trials-worker_1      | Trace:
auger-ml-trials-worker_1      | Traceback (most recent call last):
auger-ml-trials-worker_1      |   File "/var/src/auger-ml-worker/auger_ml/auger_ml/trials/AugerMLTrial.py", line 129, in _evaluate_data
auger-ml-trials-worker_1      |     CV_scores = df.splitToFolds(self.trial, self._fit_fold)
auger-ml-trials-worker_1      |   File "/var/src/auger-ml-worker/auger_ml/auger_ml/data_source/data_source_api_pandas.py", line 72, in splitToFolds
auger-ml-trials-worker_1      |     res = fold_func(options, idx, X_resampled, y_resampled, X_test1, y_test1)
auger-ml-trials-worker_1      |   File "/var/src/auger-ml-worker/auger_ml/auger_ml/trials/AugerMLTrial.py", line 110, in _fit_fold
auger-ml-trials-worker_1      |     return _score(estimator, X_test, y_test, scorer)
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/site-packages/sklearn/model_selection/_validation.py", line 528, in _score
auger-ml-trials-worker_1      |     score = scorer(estimator, X_test, y_test)
auger-ml-trials-worker_1      |   File "/usr/local/lib/python2.7/site-packages/sklearn/metrics/scorer.py", line 138, in __call__
auger-ml-trials-worker_1      |     y_pred = clf.predict_proba(X)
auger-ml-trials-worker_1      | AttributeError: 'LinearSVC' object has no attribute 'predict_proba'

**Comment by StanislavVolodarskiy** [comment]
fixed with 8d5f9166908af22d5a800d3156172d2735b73291
