### ISSUE TITLE
Reduce docker images size

### ISSUE THREAD

**Issue by skatedplrn** [deeplearninc/auger-ml#81]
Here's an example of the docker building process I'd like us to model after: https://circleci.com/workflow-run/02bc1e45-d157-4897-845a-8c6ad169c94a
https://github.com/circleci-public/dockerfile-wizard

**Comment by skatedplrn** [comment]
There are even more things we can do over what I've done so far. Check out this: https://github.com/deeplearninc/cluster-storage/blob/master/Dockerfile

There's a relatively new feature of Dockerfile that lets you chain images together. i.e.:

```FROM golang:alpine as builder
ENV RESTIC_VERSION master
WORKDIR /go/src/
RUN apk update && \
  apk add --update --no-cache \
    git \
    ca-certificates
RUN git clone https://github.com/restic/restic --branch $RESTIC_VERSION
RUN cd restic && \
  go run build.go

############# 
FROM alpine:3.7
RUN apk update && \
  apk add --update --no-cache \
    ca-certificates
WORKDIR /usr/bin/
ADD . /usr/bin/
COPY --from=builder /go/src/restic/restic /usr/bin/restic
CMD ["/usr/bin/restic"]```
See how that build will copy `--from=builder`?
We can use one image to build everything, and a second, empty image to install everything
Using this approach, the `cluster-storage` docker image we have is only 6MB

In this example it was trivial because I"m just building a golang binary, so I just copy a single binary into an alpine linux image
For python it's more complicated because we need to make sure the image has all of the runtime stuff there
But it's a similar idea I think we can try.

**Comment by knobotz** [comment]
They're called "multi-stage" docker builds. Here's an example multi-stage docker build for python: https://lekum.org/post/multistage-dockerfile/

```Dockerfile
FROM python:3 as python-base
COPY requirements.txt .
RUN pip install -r requirements.txt

FROM python:3-alpine
COPY --from=python-base /root/.cache /root/.cache
COPY --from=python-base requirements.txt .
RUN pip install -r requirements.txt && rm -rf /root/.cache
```

Each `FROM` declaration creates a new docker image, so the second one image in this example would be the runtime image used in clusters.

**Comment by knobotz** [comment]
There's also `pex`, which can help with copying dependencies and packaging applications as a single binary: https://github.com/pantsbuild/pex

**Comment by StanislavVolodarskiy** [comment]
Please find possible solution: https://github.com/deeplearninc/auger-ml/commit/50106f5f9e36275b86564885c1aa015538d85466
worker.tar.gz is about 152Mb.
