### ISSUE TITLE
Evaluating several algs in search space with PSOOptimizer only uses one alg

### ISSUE THREAD

**Issue by derekflint** [deeplearninc/auger-ml#86]
While running auger notebook on master I set config to use PSOOptimizer and then selected 6 different learning algorithms to use in the search space. When I run I only see one learning algorithm returned to leaderboard. The accuracy is low as well. If I then remove this learning algorithm from search space and run again it just shows a different learning algorithm but only that one.  

It does not seem to be evaluating the entire search space to return the best results.

I'm testing iris dataset.

**Comment by knobotz** [comment]
@derekflint I see this as well. I ran the bikesharing hour dataset with PSOOptimizer and 6 learning algorithms: LassoLarsCV, RandomForestRegressor, XGBRegressor, GradientBoostingRegressor, KNeighborsRegressor, AdaBoostRegressor, ExtraTreesRegressor

Below is a snapshot of the leaderboard, and all 100 results in the leaderboard are of type `GradientBoostingRegressor`.

<img width="898" alt="screen shot 2018-03-28 at 2 24 18 pm" src="https://user-images.githubusercontent.com/30328334/38057362-05424586-3294-11e8-88b8-8215048acbe4.png">

**Comment by derekflint** [comment]
@knobotz i noticed it with NelderMeadOptimizer  as well. I think its the sequential optimizers run one at a time. If you have 300 trials then one learning algorithm might explore thousands of pipelines so you never get to the next learning algorithm.

Just a guess.
